### ISSUE TITLE
Convert to constant

### ISSUE THREAD

**Issue by wvengen** [olbrich/ruby-units#114]
I'd like to know how many times one unit fits into another one, like this:

``` ruby
u = Unit.new("1 kg")
v = Unit.new("100 g")
quot = u / v.convert_to(u.units)
# => 10
```

This works pretty well. But when the unit is a constant, `u.units` returns an empty string, which `convert_to` doesn't like.

Of course I could use something like `v.convert_to(v.units.blank? ? "1" : v.units)`. But would it make sense to have `#units` return "1" when it is a constant?

**EDIT** corrected typo in convert_to(...)

**Comment by olbrich** [comment]
The 'units' method is intended to return just the 'unit' portion without the scalar.

Can you give me an example of one that fails?  

Incidentally, you may find that this approach works better...

    u = Unit.new('1 kg')
    v = Unit.new('100 g')
    quot = (u/v).to_base.to_f   #=> 10

If u and v are compatible units then quot should be a float.  If the quot has a unit left over then this will raise an exception because you can't convert anything but a unitless value to a float.

**Comment by wvengen** [comment]
Thanks, `#to_base` is great!

```ruby
u = Unit.new("10")
v = Unit.new("1 pc")
(u/v).to_base
# => 10
u / v.convert_to(u.units)
# ArgumentError: No Unit Specified
```

**Comment by wvengen** [comment]
Perhaps it's an idea to document `#to_base` in the README?
