### ISSUE TITLE
ruby-units overriding integer division

### ISSUE THREAD

**Issue by alexwdaniel** [olbrich/ruby-units#134]
Running into an issue with ruby-units overriding integer division. It looks to be a result of requiring 'mathn' in ruby_units/math.rb. Is this needed outside of ruby-units or would it be possible to restrict the behavior to the gem?

**Comment by olbrich** [comment]
mathn is part of the ruby standard library.  The current version of ruby-units requires it in order to ensure calculations are accurate.  There is not currently any way to scope that behavior.

If you are having issues with another gem breaking because mathn is required, I suggest you file a bug with them to fix their code.  If your own code is broken, I would be happy to help you refactor it.

**Comment by johanlunds** [comment]
This could have big consequences in completely unrelated parts of a program. I would suggest at least a disclaimer in the README informing that including `ruby-units` will affect how math calculations are done in Ruby.

I had no idea `ruby-units` did this, and just tracked down a rounding vs truncation error in a completely unrelated part of a Rails app that did datetime parsing and had nothing to do with `ruby-units`.

```ruby
# Execute as: ruby test.rb

# Output with this require: "729672532967/500" == 1459345065.934
# Output without this require: "1459345065"
require 'ruby-units'

puts(1459345065934 / 1000)
```

For anyone in the future that comes here and doesn't know what `mathn` in Ruby is: http://ruby-doc.org/stdlib-2.0.0/libdoc/mathn/rdoc/Numeric.html

> **mathn is a library for changing the way Ruby does math.** If you need more precise rounding with multiple division or exponentiation operations, then mathn is the right tool.

I didn't know about it's existence, and I have been programming Ruby since 2007.

**Comment by johanlunds** [comment]
Could any of these be alternatives to avoid requiring `mathn`?

* use Rational
* use BigDecimal

**Comment by johanlunds** [comment]
For our use case switching to https://github.com/mhuggins/ruby-measurement worked and gave about a 1000x performance boost.
