### ISSUE TITLE
multiplication exception 

### ISSUE THREAD

**Issue by pinkynrg** [olbrich/ruby-units#154]
```ruby 
1 * Unit.new("1 tempK") # ArgumentError: Cannot multiply by temperatures
```

**Comment by rage-shadowman** [comment]
Try:

    1 * Unit.new("1 degK")

The "temp" units are 0-kelvin relative and cannot be used in most math operations, while "deg" units are not relative to any base temperature and can be used in math operations. So, "32 tempF" is the freezing point of water, while "32 degF" is just a representation of 32 degrees which has nothing to do with the freezing point of water, although it could be added to "0 tempF" to get the freezing point of water.

As an example of why you can't do math with "temp" units... Should 2 * "32 tempF" be "64 tempF" (2 * 32) or should it be "526 tempF" (since 32 tempF ~ 273 tempK, thus 2 * 273 Kelvin in Fahrenheit)?
