### ISSUE TITLE
tempK - degK why not using alias?

### ISSUE THREAD

**Issue by pinkynrg** [olbrich/ruby-units#155]
there seems to be the following list of temperatures (listing the names):
- kelvin
- tempK
- celsius
- fahrenheit
- rankine
- tempC
- tempF
- tempR

why isn't tempK, for example, just an alias of kelvin? 
same thing for tempC and celsius and the rest of them?

**Comment by olbrich** [comment]
`tempK` and `degK` are two subtly different things.  `tempK` represents a temperature that is an offset from absolute zero, where `degK` just represents a degree of the same size that is not fixed relative to a reference point.  There are certain operations that behave differently when doing conversions..
```
Unit.new('100 tempK').to('tempC') #=> -173.15 tempC
Unit.new('100 degK').to('degC') #=> 100 degC
```

I don't use the alias for the proper name because it makes the distinction ambiguous.

**Comment by pinkynrg** [comment]
Oh i see so if i had to represent the conversion with an equation: 
y = kx + n
basically with k as the slope and the n as the y intersept.
