### ISSUE TITLE
Unit not recognized error after 4.0.0 upgrade

### ISSUE THREAD

**Issue by smathieu** [olbrich/ruby-units#330]
We had some definitions that worked with the 3.0.0 release that are now failing after the upgrade.

Here's a short script to reproduce the issue:

```ruby
require "ruby-units"

Unit.define("m2") do |u|
  u.definition = Unit.new("1 m") * Unit.new("1 m")
  u.display_name = "m^2"
  u.aliases = ["m²", "square_meter"]
end

puts Unit.new("1 m2") # => 1 m^2
puts Unit.new("1 square_meter") # => raise(ArgumentError, "'#{passed_unit_string}' Unit not recognized") unless used.empty?
```

This works in the 3.0.0 release, but raises an exception in the latest release. This does not seem to be an intended change.

**Comment by olbrich** [comment]
I think the problem here is the `_` in the alias name.  The parsing algorithm strips those out so that numbers can be passed in like `1_000_000`, but it also impacts the unit name. I'll look into making that a little more specific so that it only strips out underscores in numbers, but you might be able to use a `-` instead in the meantime.

See https://github.com/olbrich/ruby-units/blob/e90fc78713e009689cd9bd64415f7caa9fc8086e/lib/ruby_units/unit.rb#L1584

**Comment by smathieu** [comment]
Thanks for the quick response! This isn't super urgent, but is preventing us from updating. The `square_meter` strings comes from an external API, so we can't control this.

**Comment by olbrich** [comment]
@smathieu can you please verify if the branch associated with #331 fixes your issue?
