### ISSUE TITLE
Extending `Numeric` class

### ISSUE THREAD

**Issue by kalashnikovisme** [olbrich/ruby-units#367]
Does this gem need an optional extending `Numeric` with simple unit methods?

```ruby
1.mm     # unit = Unit.new("1 mm")
```

If this gem needs something like this, I will implement this with a Pull Request :slightly_smiling_face:

The one thing I need is the list of units that you think should be in the `Numeric` class.

**Comment by olbrich** [comment]
@kalashnikovisme Thank you for the suggestion.  I considered an approach like this in the past, but there are several reasons I opted not to implement it.

I'm trying to keep the number of places I modify / monkey-patch standard lib classes to a minimum, as that is generally considered to be a bad practice for a library like this.  There is a real risk of collisions with other libraries.

For example, ActiveSupport has methods for `1.day`, `1.minute`, `1.second`, etc.  Since this library is often used in Rails applications, the proposed approach would cause conflicts for many users.  

There are also many places where unit names would violate standard ruby method naming conventions (for example, any unit with a leading capital letter).  While it's possible to define them anyway, this has the potential to introduce confusion, trigger unintended rubocop warnings, and otherwise cause issues with IDEs.

I haven't tested it, but I also suspect that defining hundreds (thousands?) of methods on all numeric classes that aren't used will have a negative impact on memory usage and performance.

For these reasons I do not currently plan to implement this approach, but please feel free to experiment further with it and let me know what you find.

**Comment by kalashnikovisme** [comment]
Thanks, @olbrich!

Yeah, I already experimented with this approach by defining certain needed methods (distance units for example), and will come back sometime with a story about it :slightly_smiling_face: 

Thank you for the great gem and your work :slightly_smiling_face:
